"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv # https://github.com/henriquebastos/python-decouple
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-2ka&z=h=$7he&@y9k96kefhvfdvnd$oi)b&vuo+ol+z+jeqg22')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # ===[Default Django Apps]===
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ======[External Apps]======
    'django_cas_ng',
    'hijack.contrib.admin',
    'hijack',
    'private_storage',
    'crispy_forms',
    "crispy_bootstrap4",
    # =======[My Own Apps]=======
    'apps.services',
    'apps.landingpage',
    'apps.authentication',
    'apps.main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_cas_ng.middleware.CASMiddleware',
    'hijack.middleware.HijackUserMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # custom tempat
                'apps.services.context_processors.global_settings',
                'apps.services.context_processors.pertemuan_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
       'ENGINE'     : config('DB_ENGINE',   default=None), # <= 'django.db.backends.postgresql'
       'NAME'       : config('DB_NAME',     default=None), # <= 'YOUR_DB_NAME'
       'USER'       : config('DB_USER',     default=None), # <= 'YOUR_DB_USER'
       'PASSWORD'   : config('DB_PASSWORD', default=None), # <= 'YOUR_DB_PASSWORD'
       'HOST'       : config('DB_HOST',     default=None), # <= '127.0.0.1'
       'PORT'       : config('DB_PORT',     default=5432, cast=int), # <= '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static') ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom authentication backend
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.AllowAllUsersModelBackend', # If activated at login is_active is checked manually not to be one in authenticate() function
    'django.contrib.auth.backends.ModelBackend', # For django cas
    # 'django_cas_ng.backends.CASBackend', # Default django cas backend
    'apps.services.djangocas.CustomCASBackend', # Custom django cas backend
]


# WhiteNoise setting
# https://whitenoise.readthedocs.io/en/stable/
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



# =====================================================================================================
#                                           EXTENDS SETTINGS
# =====================================================================================================
# =======[Crispy]======
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"


# =======[App Info]======
APP_SHORT_NAME          = 'MyAIK'
APP_FULL_NAME           = 'PRESENSI AIK TERINTEGRASI SIHRD'
APP_VERSION             = 'v1.0'
APP_YEAR                = '2025' # Year the application was created
APP_DEVELOPER           = 'DSTI'
APP_COMPANY_SHORT_NAME  = 'UMS'
APP_COMPANY_FULL_NAME   = 'Universitas Muhammadiyah Surakarta'
APP_LOGO                = os.path.join(STATIC_URL,'images/logo/ums_logo_color.svg')
APP_FAVICON             = os.path.join(STATIC_URL,'images/logo/ums_logo_favicon.ico')



# =====[Media Files]=====
MEDIA_ROOT              = os.path.join(BASE_DIR,'media')
MEDIA_URL               = '/media/'

# PERHATIAN : Gunakan PrivateFileField atau PrivateImageField (bukan FileField/ImageField) agar file disimpan secara privat (django-private-storage).
# CARA IMPORT : from private_storage.fields import PrivateFileField, PrivateImageField
PRIVATE_STORAGE_ROOT            = os.path.join(BASE_DIR, 'media_private')
PRIVATE_STORAGE_AUTH_FUNCTION   = 'private_storage.permissions.allow_authenticated'


# ======[Login URL]======
LOGIN_URL               = 'authentication:signin'
LOGIN_REDIRECT_URL      = 'authentication:signin'


# ======[Django Cas]=====
CAS_SERVER_URL          = config('CAS_SERVER_URL', default=None) # 'https://auth.ums.ac.id/cas/'
CAS_ADMIN_PREFIX        = 'admin' # Set to -> '/admin' if you want to login to the admin using cas
CAS_CREATE_USER         = True
CAS_LOGIN_MSG           = 'Login succeeded. Welcome, %s.'
CAS_LOGGED_MSG          = 'You are logged in as %s.'
CAS_LOGIN_URL_NAME      = 'authentication:cas_ng_login'
CAS_LOGOUT_URL_NAME     = 'authentication:cas_ng_logout'
CAS_LOGOUT_COMPLETELY   = config('CAS_LOGOUT_COMPLETELY', default=True, cast=bool)
CAS_IGNORE_REFERER      = True
CAS_REDIRECT_URL        = 'main:dashboard' # Redirect after login
CAS_VERSION             = config('CAS_VERSION', default='3')


# =====[API GATEWAY]=====
# This is only optional if you want to sync user profiles with the SIHRD API.
# It is used to sync cas login data with Sihrd API (apps.services.utils.profilesync)
# if you don't have an apigateway account, please create an account at https://api.ums.ac.id/admin/
API_GATEWAY_URL         = config('API_GATEWAY_URL',      default=None) # <= 'https://api.ums.ac.id/' or 'http://172.16.10.241:8008/'
API_GATEWAY_USERNAME    = config('API_GATEWAY_USERNAME', default=None) # <= 'YOUR_APIGATEWAY_USERNAME'
API_GATEWAY_PASSWORD    = config('API_GATEWAY_PASSWORD', default=None) # <= 'YOUR_APIGATEWAY_PASSWORD'
API_GATEWAY_KEY         = os.path.join(BASE_DIR, 'apps', 'services', 'api-gateway-key.pub')
API_GATEWAY_ALGO        = ['RS256']
API_GATEWAY_VERIFY      = False # verify signature jwt


# =======[API STAR]======
# this is only optional if you don't use apistar it can be ignored
API_STAR_URL            = config('API_STAR_URL',        default=None) # <= 'https://star.ums.ac.id/abubakar/'
API_STAR_USERNAME       = config('API_STAR_USERNAME',   default=None) # <= 'YOUR_API_STAR_USERNAME'
API_STAR_PASSWORD       = config('API_STAR_PASSWORD',   default=None) # <= 'YOUR_API_STAR_PASSWORD'


# ========[EMAIL]========
# this is only optional if you don't use email it can be ignored
EMAIL_BACKEND           = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER         = config('EMAIL_HOST_USER',     default=None) # <= 'YOUR_EMAIL@GOOGLE.COM'
EMAIL_HOST_PASSWORD     = config('EMAIL_HOST_PASSWORD', default=None) # <= 'YOUR_PASSWORD'
EMAIL_HOST              = 'smtp.gmail.com'
EMAIL_PORT              = 587
EMAIL_USE_TLS           = True


# =========[WABA]========
# this is only optional
# If you don't have a secret yet, please create one at http://172.16.10.241:8020/ and contact admin for activation.
API_WHATSAPP_URL        = config('API_WHATSAPP_URL',    default=None) # <= 'http://172.16.10.241:8020/api/v1/whatsapp/
API_WHATSAPP_SECRET     = config('API_WHATSAPP_SECRET', default=None) # <= 'YOUR_SECRET'


# ======[CORS/CSRF]======
CSRF_TRUSTED_ORIGINS    = config('CSRF_TRUSTED_ORIGINS', default='https://*.ums.ac.id,http://localhost:8000', cast=Csv())


# =======[SECURE]========
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT     = False


# =======[LOGGING]=======
# https://docs.djangoproject.com/en/5.1/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': { 'class': 'logging.StreamHandler', },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'main': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'services': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
