# Generated by Django 5.2.8 on 2025-12-10 04:02

import apps.main.models.m_setting
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, null=True)),
                ('key', models.CharField(max_length=250, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('mode', models.CharField(choices=[('char', 'CHAR'), ('text', 'TEXT'), ('file', 'FILE'), ('charfile', 'CHARFILE'), ('textfile', 'TEXTFILE')], max_length=10, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('file', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.main.models.m_setting.path_file)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
