# Generated by Django 5.2.8 on 2025-12-13 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pembicara', models.CharField(max_length=256)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('mulai', models.DateTimeField(blank=True, null=True)),
                ('akhir', models.DateTimeField(blank=True, null=True)),
                ('presensi_mulai', models.DateTimeField(blank=True, null=True)),
                ('presensi_akhir', models.DateTimeField(blank=True, null=True)),
                ('tautan', models.URLField(blank=True, null=True)),
                ('materi', models.FileField(blank=True, null=True, upload_to='materi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipePertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangkuman', models.TextField()),
                ('berkas_rangkuman', models.FileField(blank=True, null=True, upload_to='rangkuman/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pertemuan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pertemuan')),
                ('peserta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pertemuan',
            name='tipe_pertemuan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tipepertemuan'),
        ),
    ]
