# Generated by Django 5.2.8 on 2025-12-13 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pertemuan_tipepertemuan_presensi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together={('pertemuan', 'peserta')},
        ),
    ]
