# Generated by Django 5.2.8 on 2025-12-17 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_presensi_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_lembaga', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('namasingkat', models.CharField(max_length=255)),
                ('jenis_id', models.IntegerField(blank=True, null=True)),
                ('jenis', models.CharField(blank=True, max_length=100, null=True)),
                ('subjenis_id', models.IntegerField(blank=True, null=True)),
                ('subjenis', models.CharField(blank=True, max_length=100, null=True)),
                ('unitpendahulu', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('superunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.lembaga')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
