# Generated by Django 5.2.8 on 2025-12-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lembaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembaga',
            name='namasingkat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
