# Generated by Django 5.2.8 on 2025-12-17 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lembaga_namasingkat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jabatan', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('eselon', models.CharField(blank=True, max_length=100, null=True)),
                ('sks', models.IntegerField(blank=True, null=True)),
                ('uniid_penjabat', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lembaga')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
