# Generated by Django 5.2.8 on 2025-12-17 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.lembaga'),
        ),
    ]
