# Generated by Django 5.2.8 on 2025-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_jabatan_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipepertemuan',
            name='has_sertifikat',
            field=models.BooleanField(default=False),
        ),
    ]
