# Generated by Django 5.2.8 on 2025-12-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tipepertemuan_has_sertifikat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='sertifikat_position',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
