# Generated by Django 5.2.8 on 2025-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pertemuan_sertifikat_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='sertifikat',
            field=models.FileField(blank=True, null=True, upload_to='sertifikat/'),
        ),
    ]
