# Generated by Django 5.2.8 on 2026-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pertemuan_sertifikat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='jumlah_pengunjung_tautan',
            field=models.IntegerField(default=0),
        ),
    ]
