# Generated by Django 5.2.8 on 2025-12-10 04:02

import apps.authentication.models.profile
import django.core.validators
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='groupdetails', serialize=False, to='auth.group')),
                ('alias', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nip', models.CharField(blank=True, max_length=20, null=True)),
                ('nidn', models.CharField(blank=True, max_length=50, null=True)),
                ('ext_email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_dosen', models.IntegerField(blank=True, null=True)),
                ('home_id', models.CharField(blank=True, max_length=20, null=True)),
                ('homebase', models.CharField(blank=True, max_length=255, null=True)),
                ('image', private_storage.fields.PrivateImageField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=apps.authentication.models.profile.path_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('otp', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
