# Generated by Django 5.2.8 on 2026-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tanggalmulaimasuk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
