# Generated by Django 5.2.8 on 2026-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_tanggalmulaimasuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kepegawaian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
